service: StringTools

provider:
  name: aws
  runtime: dotnetcore3.1
  region: eu-west-1
  stage: demo

package:
  individually: true

functions:
  isPalindrome:
    handler: StringTools::StringTools.IsPalindrome::Handler
    package:
      artifact: bin/Release/netcoreapp3.1/StringTools.IsPalindrome.zip
    events:
      - http:
          path: api/isPalindrome
          method: post